{% set version = "4.1.3" %}

package:
  name: jupyterhub-feedstock
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/jupyterhub/jupyterhub-{{ version }}.tar.gz
  sha256: eb547161c5709744a45073d878f3e0c96540859a2e6419931c36eef7ce888b82

build:
  number: 0
  noarch: python

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7

outputs:
  - name: jupyterhub-base
    build:
      noarch: python
      script: {{ PYTHON }} -m pip install . --no-deps -vv
      entry_points:
        - jupyterhub = jupyterhub.app:main
        - jupyterhub-singleuser = jupyterhub.singleuser:main
    requirements:
      host:
        - python >=3.7
        - pip
      run:
        - __{{ noarch_platform }}
        - alembic >=1.4
        - async_generator >=1.9
        - certipy >=0.1.2
        - importlib-metadata >=3.6  # not actually required for Python >=3.10
        - jinja2 >=2.11.0
        - jupyter_telemetry >=0.1.0
        - oauthlib >=3.0
        - packaging
        {% if noarch_platform == "unix" %}
        - pamela
        {% else %}
        - psutil
        {% endif %}
        - prometheus_client >=0.4.0
        - python >=3.7
        - python-dateutil
        - requests
        - sqlalchemy >=1.4
        - tornado >=5.1
        - traitlets >=4.3.2
      run_constrained:
        - psutil >=5.6.5

    test:
      requires:
        - pip
      imports:
        - jupyterhub
        - jupyterhub.apihandlers
        - jupyterhub.handlers
        - jupyterhub.tests
        - jupyterhub.app
      commands:
        - pip check
        - jupyterhub --help-all
        {% if noarch_platform == "unix" %}
        - test -f $PREFIX/share/jupyterhub/templates/page.html
        - test -f $PREFIX/share/jupyterhub/static/components/jquery/dist/jquery.min.js
        - test -f $PREFIX/share/jupyterhub/static/css/style.min.css
        - test -f $PREFIX/share/jupyterhub/static/js/home.js
        {% else %}
        - dir %PREFIX%\share\jupyterhub\templates\page.html || exit 1
        - dir %PREFIX%\share\jupyterhub\static\components\jquery\dist\jquery.min.js || exit 1
        - dir %PREFIX%\share\jupyterhub\static\css\style.min.css || exit 1
        - dir %PREFIX%\share\jupyterhub\static\js\home.js || exit 1
        {% endif %}

  - name: jupyterhub-singleuser
    build:
      noarch: python
    requirements:
      host:
        - python >=3.7
      run:
        - __{{ noarch_platform }}
        - {{ pin_subpackage("jupyterhub-base", exact=True) }}
        - jupyterlab >=3.1
        - python >=3.7
    test:
      requires:
        - pip
      imports:
        - jupyterhub.singleuser
      commands:
        - pip check
        - jupyterhub-singleuser --help-all

  - name: jupyterhub
    build:
      noarch: python
    requirements:
      host:
        - python >=3.7
      run:
        - __{{ noarch_platform }}
        - {{ pin_subpackage("jupyterhub-base", exact=True) }}
        - configurable-http-proxy >=4
        - nodejs >=12
        - psutil  # undeclared extra, used preferentially for logging
        - pycurl  # undeclared extra, used preferentially for performance
        - python >=3.7
    test:
      requires:
        - pip
      imports:
        - jupyterhub
      commands:
        - pip check
        - jupyterhub --help-all
        - configurable-http-proxy --help  # [not win]

about:
  home: https://github.com/jupyterhub/jupyterhub
  license: BSD-3-Clause
  license_file: COPYING.md
  summary: Multi-user server for Jupyter notebooks
  doc_url: https://jupyterhub.readthedocs.io

extra:
  feedstock-name: jupyterhub
  recipe-maintainers:
    - minrk
    - blink1073
    - consideRatio
    - manics
    - bollwyvl
