{% set version = "2.3.0" %}

package:
  name: jupyterhub-feedstock
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/jupyterhub/jupyterhub-{{ version }}.tar.gz
  sha256: 15e6711d2bd3dc0835f5fcc6ef1c48fef3aa2562f09e0c469c2a46af4ea9c318

build:
  number: 0
  noarch: python

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

outputs:
  - name: jupyterhub-base
    build:
      noarch: python
      script: {{ PYTHON }} -m pip install . --no-deps -vv
      entry_points:
        - jupyterhub = jupyterhub.app:main
        - jupyterhub-singleuser = jupyterhub.singleuser:main
    requirements:
      host:
        - python >=3.6
        - pip
      run:
        - alembic >=1.4
        - async_generator >=1.9
        - certipy >=0.1.2
        - entrypoints
        - jinja2 >=2.11.0
        - jupyter_telemetry >=0.1.0
        - oauthlib >=3.0
        - packaging
        - pamela
        - prometheus_client >=0.4.0
        - psutil  # undeclared extra, used preferentially for logging
        - pycurl  # undeclared extra, used preferentially for performance
        - python >=3.6
        - python-dateutil
        - requests
        - sqlalchemy >=1.1
        - tornado >=5.1
        - traitlets >=4.3.2

    test:
      requires:
        - pip
      imports:
        - jupyterhub
        - jupyterhub.apihandlers
        - jupyterhub.handlers
        - jupyterhub.tests
        - jupyterhub.app
      commands:
        - pip check
        - jupyterhub --help-all
        - test -f $PREFIX/share/jupyterhub/templates/page.html
        - test -f $PREFIX/share/jupyterhub/static/components/jquery/dist/jquery.min.js
        - test -f $PREFIX/share/jupyterhub/static/css/style.min.css
        - test -f $PREFIX/share/jupyterhub/static/js/home.js

  - name: jupyterhub-singleuser
    build:
      noarch: python
    requirements:
      host:
        - python >=3.6
      run:
        - python >=3.6
        - {{ pin_subpackage("jupyterhub-base", exact=True) }}
        - jupyterlab >=3.1
    test:
      requires:
        - pip
      imports:
        - jupyterhub.singleuser
      commands:
        - pip check
        - jupyterhub-singleuser --help-all

  - name: jupyterhub
    build:
      noarch: python
    requirements:
      host:
        - python >=3.6
      run:
        - python >=3.6
        - {{ pin_subpackage("jupyterhub-base", exact=True) }}
        - configurable-http-proxy >=4
        - nodejs >=12
    test:
      requires:
        - pip
      imports:
        - jupyterhub
      commands:
        - pip check
        - jupyterhub --help-all
        - configurable-http-proxy --help

about:
  home: https://github.com/jupyterhub/jupyterhub
  license: BSD-3-Clause
  license_file: COPYING.md
  summary: Multi-user server for Jupyter notebooks
  doc_url: https://jupyterhub.readthedocs.io

extra:
  feedstock-name: jupyterhub-feedstock
  recipe-maintainers:
    - minrk
    - blink1073
    - consideRatio
    - manics
    - bollwyvl
