{% set version = "0.9.1" %}

package:
  name: jupyterhub
  version: {{ version }}

source:
  fn: jupyterhub-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/j/jupyterhub/jupyterhub-{{ version }}.tar.gz
  sha256: daefe0df09a97d9af7157d8f28d28e0c5a415616e6337d887bba26543df10a7c

build:
  number: 0
  noarch: python
  skip: true  # [py<35]
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - alembic
    - async_generator >=1.8
    - configurable-http-proxy
    - jinja2
    - pamela  # [not win]
    - prometheus_client >=0.0.21
    - psutil  # [win]
    - pycurl
    - python-dateutil
    - python-oauth2 >=1.0
    - requests
    - sqlalchemy >=1.1
    - traitlets >=4.3.2
    - tornado >=5.0
    
test:
  imports:
    - jupyterhub
    - jupyterhub.apihandlers
    - jupyterhub.handlers
    - jupyterhub.tests
    - jupyterhub.app
  commands:
    - python -m jupyterhub --help-all
    - test -f ${PREFIX}/share/jupyterhub/static/css/style.min.css  # [unix]
    - test -f ${PREFIX}/share/jupyterhub/templates/page.html  # [unix]

about:
  home: https://github.com/jupyterhub/jupyterhub
  license: BSD 3-Clause
  license_file: COPYING.md
  summary: Multi-user server for Jupyter notebooks

extra:
  recipe-maintainers:
    - minrk
