# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "5.4.3"
  python_check_max: 3.14

recipe:
  name: jupyterhub
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/j/jupyterhub/jupyterhub-${{ version }}.tar.gz
  sha256: 2411a3eabe46d53995122ba05a0a0857c5aa228184802b724d99eb43b3faf888

build:
  number: 0
  noarch: python

outputs:
  - package:
      name: jupyterhub-base
      version: ${{ version }}
    build:
      noarch: python
      script:
        - python -m pip install . --no-deps -vv --no-build-isolation --disable-pip-version-check
      python:
        entry_points:
          - jupyterhub = jupyterhub.app:main
          - jupyterhub-singleuser = jupyterhub.singleuser:main
    requirements:
      host:
        - pip
        - python ${{ python_min }}.*
        - setuptools
        - setuptools-scm
      run:
        - __${{ noarch_platform }}
        - alembic >=1.4
        - certipy >=0.1.2
        - idna
        - jinja2 >=2.11.0
        - jupyter_events
        - oauthlib >=3.0
        - packaging
        - prometheus_client >=0.5.0
        - pydantic >=2
        - python >=${{ python_min }}
        - python-dateutil
        - requests
        - sqlalchemy >=1.4.1
        - tornado >=5.1
        - traitlets >=4.3.2
        - if: noarch_platform == "unix"
          then:
            - pamela
          else:
            - psutil
      run_constraints:
        - psutil >=5.6.5
        - pamela >=1.1.0
    tests:
      - package_contents:
          files:
            - share/jupyterhub/templates/page.html
            - share/jupyterhub/static/components/jquery/dist/jquery.min.js
            - share/jupyterhub/static/css/style.min.css
            - share/jupyterhub/static/js/home.js
      - python:
          pip_check: true
          python_version:
            - ${{ python_min }}.*
            - ${{ python_check_max }}.*
          imports:
            - jupyterhub
            - jupyterhub.apihandlers
            - jupyterhub.handlers
            - jupyterhub.app
      - requirements:
          run:
            - pip
            - python ${{ python_min }}.*
        script:
          - python -m pip list --format=freeze
          - python -m pip list --format=freeze | python -c "import sys; assert 'jupyterhub==${{ version }}' in sys.stdin.read()"
          - jupyterhub --version
          - jupyterhub --version | python -c "import sys; assert sys.stdin.read().strip() == '${{ version }}'"
          - jupyterhub --help-all

  - package:
      name: jupyterhub-singleuser
      version: ${{ version }}
    build:
      noarch: generic
    requirements:
      run:
        - __${{ noarch_platform }}
        - ${{ pin_subpackage("jupyterhub-base", exact=True) }}
        - jupyterlab >=3.1
    tests:
      - python:
          imports: jupyterhub.singleuser
          pip_check: true
          python_version:
            - ${{ python_min }}.*
            - ${{ python_check_max }}.*
      - requirements:
          run:
            - python ${{ python_min }}.*
        script:
          - jupyterhub-singleuser --help-all

  - package:
      name: jupyterhub
      version: ${{ version }}
    build:
      noarch: generic
    requirements:
      run:
        - __${{ noarch_platform }}
        - ${{ pin_subpackage("jupyterhub-base", exact=True) }}
        - configurable-http-proxy >=4
        - nodejs >=12
        - psutil # undeclared extra, used preferentially for logging
        - pycurl # undeclared extra, used preferentially for performance
    tests:
      - python:
          imports: jupyterhub
          pip_check: true
          python_version:
            - ${{ python_min }}.*
            - ${{ python_check_max }}.*
      - script:
          - jupyterhub --help-all
          - if: noarch_platform == "unix"
            then:
              - configurable-http-proxy --help

about:
  homepage: https://hub.jupyter.org
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - share/jupyterhub/static/components/@fortawesome/fontawesome-free/LICENSE.txt
    - share/jupyterhub/static/components/bootstrap/LICENSE
    - share/jupyterhub/static/components/jquery/LICENSE.txt
    - share/jupyterhub/static/components/moment/LICENSE
    - share/jupyterhub/static/js/admin-react.js.LICENSE.txt
  summary: A multi-user server for Jupyter notebooks
  repository: https://github.com/jupyterhub/jupyterhub
  documentation: https://jupyterhub.readthedocs.io

extra:
  feedstock-name: jupyterhub
  recipe-maintainers:
    - minrk
    - blink1073
    - consideRatio
    - manics
    - bollwyvl
