# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: 5.3.0
  python_check_max: 3.13

recipe:
  name: jupyterhub

source:
  url: https://pypi.org/packages/source/j/jupyterhub/jupyterhub-{{ version }}.tar.gz
  sha256: 57834b36e7db8f26f21d9aeba1e1d5b8c91b9ff14a7c144097178977aa1e723f

build:
  number: 0
  noarch: python

outputs:
  - package:
      name: jupyterhub-base
    build:
      noarch: python
      script:
        - python -m pip install . --no-deps -vv --no-build-isolation --disable-pip-version-check
      python:
        entry_points:
          - jupyterhub = jupyterhub.app:main
          - jupyterhub-singleuser = jupyterhub.singleuser:main
    requirements:
      host:
        - pip
        - python ${{ python_min }}.*
        - setuptools
        - setuptools-scm
      run:
        - __${{ noarch_platform }}
        - alembic >=1.4
        - async_generator >=1.9 # not actually required for Python >=3.10
        - certipy >=0.1.2
        - idna
        - importlib-metadata >=3.6 # not actually required for Python >=3.10
        - jinja2 >=2.11.0
        - jupyter_events
        - oauthlib >=3.0
        - packaging
        - prometheus_client >=0.5.0
        - pydantic >=2
        - python >=${{ python_min }}
        - python-dateutil
        - requests
        - sqlalchemy >=1.4.1
        - tornado >=5.1
        - traitlets >=4.3.2
        - if: noarch_platform == "unix"
          then:
            - pamela
          else:
            - psutil
      run_constraints:
        - psutil >=5.6.5
        - pamela >=1.1.0
    tests:
      - python:
          pip_check: true
          python_version:
            - ${{ python_min }}.*
            - ${{ python_check_max }}.*
          imports:
            - jupyterhub
            - jupyterhub.apihandlers
            - jupyterhub.handlers
            - jupyterhub.app
      - script:
          - jupyterhub --help-all
          - if: noarch_platform == "unix"
            then:
              - test -f $PREFIX/share/jupyterhub/templates/page.html
              - test -f $PREFIX/share/jupyterhub/static/components/jquery/dist/jquery.min.js
              - test -f $PREFIX/share/jupyterhub/static/css/style.min.css
              - test -f $PREFIX/share/jupyterhub/static/js/home.js
            else:
              - dir %PREFIX%\share\jupyterhub\templates\page.html                         || exit 1
              - dir %PREFIX%\share\jupyterhub\static\components\jquery\dist\jquery.min.js || exit 1
              - dir %PREFIX%\share\jupyterhub\static\css\style.min.css                    || exit 1
              - dir %PREFIX%\share\jupyterhub\static\js\home.js                           || exit 1

  - package:
      name: jupyterhub-singleuser
    build:
      noarch: generic
    requirements:
      run:
        - __{{ noarch_platform }}
        - ${{ pin_subpackage("jupyterhub-base", exact=True) }}
        - jupyterlab >=3.1
    tests:
      - python:
          imports: jupyterhub.singleuser
          pip_check: true
          python_version:
            - ${{ python_min }}.*
            - ${{ python_check_max }}.*
      - script:
        - jupyterhub-singleuser --help-all

  - package:
      name: jupyterhub
    build:
      noarch: generic
    requirements:
      run:
        - __{{ noarch_platform }}
        - ${{ pin_subpackage("jupyterhub-base", exact=True) }}
        - configurable-http-proxy >=4
        - nodejs >=12
        - psutil  # undeclared extra, used preferentially for logging
        - pycurl  # undeclared extra, used preferentially for performance
    tests:
      - python:
          imports: jupyterhub.singleuser
          pip_check: true
          python_version:
            - ${{ python_min }}.*
            - ${{ python_check_max }}.*
      - script:
        - jupyterhub --help-all
        - if: noarch_platform == "unix"
          then:
            - configurable-http-proxy --help

about:
  homepage: https://hub.jupyter.org
  license: BSD-3-Clause
  license_file: LICENSE
  summary: A multi-user server for Jupyter notebooks
  repository: https://github.com/jupyterhub/jupyterhub
  documentation: https://jupyterhub.readthedocs.io

extra:
  feedstock-name: jupyterhub
  recipe-maintainers:
    - minrk
    - blink1073
    - consideRatio
    - manics
    - bollwyvl
