azure:
  store_build_artifacts: true
bot:
  automerge: true
  inspection: hint-grayskull
conda_build:
  pkg_format: "2"
conda_build_tool: rattler-build
conda_forge_output_validation: true
conda_install_tool: pixi
github:
  branch_name: main
  tooling_branch_name: main
noarch_platforms:
  - linux_64
  - win_64
