azure:
  store_build_artifacts: true
bot:
  automerge: true
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
noarch_platforms:
- linux_64
- win_64
provider:
  linux_aarch64: default
  linux_ppc64le: default
  win: azure
conda_build:
  pkg_format: '2'
